version: '3.8'

services:
  discovery-server:
    build:
      context: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: smartbazaar
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    depends_on:
      - mysql-db
      - discovery-server
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/smartbazaar
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin

  price-service:
    build:
      context: ./price-service
    container_name: price-service
    depends_on:
      - mysql-db
      - discovery-server
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/smartbazaar
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    depends_on:
      - discovery-server
      - product-service
      - price-service
    ports:
      - "8080:8080"

  smartbazaar-ui:
    build:
      context: ./smartbazaar-ui
      args:
        #REACT_APP_API_URL: http://api-gateway:8080
        REACT_APP_API_URL: http://localhost:8080
    container_name: smartbazaar-ui
    ports:
      - "3000:80"
    depends_on:
      - api-gateway

volumes:
  mysql-data:
